# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Test

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.actor == 'dependabot[bot]' }}
        run: echo "Skipping - Will be tested in dependabot-merge"
      - uses: actions/checkout@v2.4.0
        if: ${{ github.actor != 'dependabot[bot]' }}
      - uses: actions/setup-node@v2.5.1
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
        if: ${{ github.actor != 'dependabot[bot]' }}
      - run: npm run build
        if: ${{ github.actor != 'dependabot[bot]' }}
      - run: npm run lint
        if: ${{ github.actor != 'dependabot[bot]' }}
      - run: npm run flow
        if: ${{ github.actor != 'dependabot[bot]' }}
      - uses: artiomtr/jest-coverage-report-action@v2
        if: ${{ github.actor != 'dependabot[bot]' }}
